var searchData=
[
  ['saveargaction_407',['SaveArgAction',['../structtesting_1_1internal_1_1SaveArgAction.html',1,'testing::internal']]],
  ['saveargpointeeaction_408',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1SaveArgPointeeAction.html',1,'testing::internal']]],
  ['scopedtrace_409',['ScopedTrace',['../classtesting_1_1ScopedTrace.html',1,'testing']]],
  ['secret_410',['Secret',['../classtesting_1_1internal_1_1Secret.html',1,'testing::internal']]],
  ['separateinstancetest_411',['SeparateInstanceTest',['../classSeparateInstanceTest.html',1,'']]],
  ['sequencetestinglistener_412',['SequenceTestingListener',['../classSequenceTestingListener.html',1,'']]],
  ['setargrefereeaction_413',['SetArgRefereeAction',['../structtesting_1_1internal_1_1SetArgRefereeAction.html',1,'testing::internal']]],
  ['setargumentpointeeaction_414',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1SetArgumentPointeeAction.html',1,'testing::internal']]],
  ['setarrayargumentaction_415',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1SetArrayArgumentAction.html',1,'testing::internal']]],
  ['seterrnoandreturnaction_416',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1SetErrnoAndReturnAction.html',1,'testing::internal']]],
  ['setup_417',['setUp',['../classgoogletest-filter-unittest_1_1GTestFilterUnitTest.html#a5aedf9d24243167acee87c9ddba82cc7',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['setupenvironment_418',['SetupEnvironment',['../classSetupEnvironment.html',1,'']]],
  ['setupfailtest_419',['SetupFailTest',['../classSetupFailTest.html',1,'']]],
  ['setuptestcasetest_420',['SetUpTestCaseTest',['../classtesting_1_1SetUpTestCaseTest.html',1,'testing']]],
  ['setuptestsuitetest_421',['SetUpTestSuiteTest',['../classtesting_1_1SetUpTestSuiteTest.html',1,'testing']]],
  ['skipentireenvironmenttest_422',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1SkipEntireEnvironmentTest.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1SkipEntireEnvironmentTest.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skippedtest_423',['SkippedTest',['../classSkippedTest.html',1,'']]],
  ['stackinterface_424',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1StackInterface.html',1,'testing::gmock_function_mocker_test']]],
  ['statefulnamingfunctor_425',['StatefulNamingFunctor',['../structStatefulNamingFunctor.html',1,'']]],
  ['statefulnamingtest_426',['StatefulNamingTest',['../classStatefulNamingTest.html',1,'']]],
  ['staticasserttypeeqtesthelper_427',['StaticAssertTypeEqTestHelper',['../classStaticAssertTypeEqTestHelper.html',1,'']]],
  ['stlcontainerview_428',['StlContainerView',['../classtesting_1_1internal_1_1StlContainerView.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_429',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01_1_1std_1_1tuple_3_01ElementPointer_00_01Size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_430',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01Element_0fN_0e_4.html',1,'testing::internal']]],
  ['streamableinglobal_431',['StreamableInGlobal',['../classStreamableInGlobal.html',1,'']]],
  ['streamableinlocal_432',['StreamableInLocal',['../structfoo_1_1StreamableInLocal.html',1,'foo']]],
  ['streamabletemplateinfoo_433',['StreamableTemplateInFoo',['../classfoo_1_1StreamableTemplateInFoo.html',1,'foo']]],
  ['streamprinter_434',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1StreamPrinter.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strictmock_435',['StrictMock',['../classtesting_1_1StrictMock.html',1,'testing']]],
  ['strictmockimpl_436',['StrictMockImpl',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_437',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['string_438',['String',['../classtesting_1_1internal_1_1String.html',1,'testing::internal']]],
  ['subprocess_439',['Subprocess',['../classgtest__test__utils_1_1Subprocess.html',1,'gtest_test_utils']]],
  ['successfultest_440',['SuccessfulTest',['../classSuccessfulTest.html',1,'']]],
  ['suiteapiresolver_441',['SuiteApiResolver',['../structtesting_1_1internal_1_1SuiteApiResolver.html',1,'testing::internal']]],
  ['sumof5functor_442',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1SumOf5Functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_443',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1SumOf6Functor.html',1,'testing::gmock_more_actions_test']]],
  ['supported_20platforms_444',['Supported Platforms',['../md_googletest_1_15_2_docs_platforms.html',1,'']]]
];
